name: Deploy

on:
  push:
    branches:
      - main

jobs:
    build:

        runs-on: ubuntu-latest

        defaults:
            run:
               working-directory: api

        steps:
            - name: Checkout
              uses: actions/checkout@v4 

            - name: Instalar o dotnet
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.0.x'
            
            - name: Restaurar as dependencias
              run: dotnet restore 

            - name: Compilar
              run: dotnet build

            - name: Testar
              run: dotnet test

            - name: Empacotar
              run: dotnet publish -c Release -o ./dist Fatec.Rent.Api/Fatec.Rent.Api.csproj

            - name: Deploy to Azure
              uses: azure/webapps-deploy@v2
              with:
                app-name: 'fatec-rent-a-car-api'
                publish-profile: ${{ secrets.PUBLISH_PROFILE }}
                package: ./dist

